import type { Requirement } from "@/lib/types";

export const requirements: Requirement[] = [
  {
    id: "req-001",
    study_id: "s-001",
    area_code: "TAL",
    process_code: "MTTO_PREV",
    problem: "Sin trazabilidad de refacciones consumidas por OT de mantenimiento",
    need: "Asociar refacción con número de serie/lote a la orden de trabajo y al activo",
    proposed_solution: "Workflow de consumo con lectura de código de barras y bitácora por activo",
    suggested_module: "Mantenimiento",
    priority: "critical",
    risk_level: "high",
    status: "validated",
  },
  {
    id: "req-002",
    study_id: "s-001",
    area_code: "TAL",
    process_code: "MTTO_PREV",
    problem: "Sin historial de horas de operación por herramienta",
    need: "Registrar horas de operación al retorno de pozo y acumular vida útil",
    proposed_solution: "Captura en retorno + cálculo MTBF/MTTR por modelo",
    suggested_module: "Mantenimiento",
    priority: "high",
    risk_level: "high",
    status: "in_design",
  },
  {
    id: "req-003",
    study_id: "s-001",
    area_code: "CAL",
    process_code: "INSP_NDT",
    problem: "Certificados vencen sin alerta temprana",
    need: "Control documental con vencimientos y pre-alertas a 30/15/5 días",
    proposed_solution: "Dashboard de certificados + bloqueo de despacho si vencido",
    suggested_module: "Calidad",
    priority: "critical",
    risk_level: "critical",
    status: "validated",
  },
  {
    id: "req-004",
    study_id: "s-001",
    area_code: "ALM",
    process_code: "INV_CONC",
    problem: "Inventario físico no se concilia contra sistema",
    need: "Conciliación periódica con diferencias documentadas y CAPA",
    proposed_solution: "Módulo de conteo cíclico + flujo de aprobación de ajustes",
    suggested_module: "Almacén",
    priority: "high",
    risk_level: "high",
    status: "identified",
  },
  {
    id: "req-005",
    study_id: "s-001",
    area_code: "TAL",
    process_code: "MTTO_COR",
    problem: "Herramientas fuera de especificación regresan a patio sin marcaje",
    need: "Registro de fuera-de-especificación con segregación física",
    proposed_solution: "Status operacional + ubicación lógica de cuarentena",
    suggested_module: "Calidad",
    priority: "high",
    risk_level: "high",
    status: "in_design",
  },
  {
    id: "req-006",
    study_id: "s-001",
    area_code: "AUD",
    process_code: "MOV_ALM",
    problem: "Auditoría de movimientos consume días por falta de log",
    need: "Bitácora inmutable de movimientos con quién/cuándo/qué",
    proposed_solution: "Audit trail a nivel transacción + reportes pre-armados",
    suggested_module: "Auditoría",
    priority: "medium",
    risk_level: "medium",
    status: "identified",
  },
  {
    id: "req-007",
    study_id: "s-001",
    area_code: "FIN",
    process_code: "COST_SVC",
    problem: "No se calcula costo real por activo",
    need: "Acumular mano de obra + refacciones + servicios externos por activo",
    proposed_solution: "Costeo por activo con asientos contables ligados",
    suggested_module: "Finanzas",
    priority: "medium",
    risk_level: "medium",
    status: "identified",
  },
  {
    id: "req-008",
    study_id: "s-001",
    area_code: "CAL",
    process_code: "INSP_NDT",
    problem: "Control de inspecciones vencidas se hace en Excel",
    need: "Sistema de programación con calendario y responsable",
    proposed_solution: "Plan de inspección por activo + recordatorios",
    suggested_module: "Calidad",
    priority: "high",
    risk_level: "high",
    status: "validated",
  },
];
