import type { Risk } from "@/lib/types";

const calc = (p: number, i: number) => p * i;

export const risks: Risk[] = [
  {
    id: "rk-001",
    study_id: "s-001",
    category_code: "OPERATIONAL",
    title: "Herramienta enviada a pozo sin inspección NDT vigente",
    description: "Falla en despacho permite envío de activos con MPI/UT vencido. Riesgo HSE y de reclamo del cliente.",
    probability: 4,
    impact: 5,
    criticality: calc(4, 5),
    mitigation: "Bloqueo de despacho automático si certificado vencido. Pre-alerta 30/15/5 días.",
    status: "mitigating",
    owner: "QA Manager",
  },
  {
    id: "rk-002",
    study_id: "s-001",
    category_code: "FINANCIAL",
    title: "Costos ocultos de mantenimiento no atribuidos al activo",
    description: "Refacciones y mano de obra se cargan a gasto general; el margen real por contrato es desconocido.",
    probability: 5,
    impact: 4,
    criticality: calc(5, 4),
    mitigation: "Costeo por activo + asientos ligados a OT.",
    status: "open",
    owner: "CFO",
  },
  {
    id: "rk-003",
    study_id: "s-001",
    category_code: "COMPLIANCE",
    title: "Falta de evidencia documental ante auditoría regulatoria",
    description: "Certificados, hojas viajeras y bitácoras en papel disperso. Riesgo de sanción API/ISO.",
    probability: 4,
    impact: 5,
    criticality: calc(4, 5),
    mitigation: "Repositorio documental con versionado e indexado por activo.",
    status: "mitigating",
    owner: "QA Manager",
  },
  {
    id: "rk-004",
    study_id: "s-001",
    category_code: "OPERATIONAL",
    title: "Pérdida de trazabilidad por movimientos manuales",
    description: "Salidas y retornos sin folio sistémico. No se puede reconstruir el historial de un activo.",
    probability: 5,
    impact: 4,
    criticality: calc(5, 4),
    mitigation: "Workflow obligatorio con captura en patio + firma electrónica.",
    status: "open",
    owner: "Jefe Almacén",
  },
  {
    id: "rk-005",
    study_id: "s-001",
    category_code: "OPERATIONAL",
    title: "Inventario físico no conciliado",
    description: "Diferencias entre sistema y patio no se cuantifican; riesgo de pérdida no detectada.",
    probability: 4,
    impact: 3,
    criticality: calc(4, 3),
    mitigation: "Conteo cíclico ABC + reporte mensual de diferencias.",
    status: "open",
    owner: "Jefe Almacén",
  },
  {
    id: "rk-006",
    study_id: "s-001",
    category_code: "OPERATIONAL",
    title: "Refacciones sin lote/proveedor asociado",
    description: "Imposible rastrear refacciones defectuosas al lote/proveedor ante falla en pozo.",
    probability: 3,
    impact: 4,
    criticality: calc(3, 4),
    mitigation: "Recepción con captura de lote/serie obligatoria.",
    status: "open",
    owner: "Jefe Compras",
  },
];
